WIP (add pdfinfo and pdffonts checks)

diff --git a/Documentation/pdf_makefile b/Documentation/pdf_makefile
--- a/Documentation/pdf_makefile
+++ b/Documentation/pdf_makefile
@@ -29,25 +29,56 @@ symlink-pdf:
 	)
 endif #UNEXPECTED_DIR
 
-check-pdf: TEXSOURCES := $(shell find $(abspath $(BUILDDIR)) -wholename "$(abspath $(BUILDDIR))/*latex/*.tex")
+check-pdf: TEXSOURCES = $(shell find $(abspath $(BUILDDIR)) -wholename "$(abspath $(BUILDDIR))/*latex/*.tex")
 
 PAT_OK = "DEADPATTERN"
 ifneq ($(V),1)
 PAT_OK = "OK"
 endif
 
+PDFINFO_CMD = $(shell which pdfinfo)
+PDFFONTS_CMD = $(shell which pdffonts)
+
 check-pdf:
-	@echo "Checking PDFs ..."
+ifneq ($(PDFINFO_CMD),)
+	@echo "Checking PDFs with $(PDFINFO_CMD) ..."
 	@for f in $(subst .tex,.pdf,$(TEXSOURCES)) ; do \
 	    if [ -e $$f ] ; then \
 	        if pdfinfo "$$f" > /dev/null ; then \
 	            echo "$$f: OK" ; \
 	        else \
 	            echo "$$f: NG" ; \
-		fi \
+	        fi \
 	    else \
 		echo "$$f: not found!" ; \
 	    fi \
 	done | sort | grep -v $(PAT_OK) || true
+else # PDFINFO_CMD
+	@echo 'Checking expected PDFs ("pdfinfo" unavailable) ...'
+	@for f in $(subst .tex,.pdf,$(TEXSOURCES)) ; do \
+	    if [ -e $$f ] ; then \
+	        echo "$$f: OK" ; \
+	    else \
+		echo "$$f: not found!" ; \
+	    fi \
+	done | sort | grep -v $(PAT_OK) || true
+endif # PDFINFO_CMD
+ifneq ($(PDFFONTS_CMD),)
+	@for f in $(subst .tex,.pdf,$(TEXSOURCES)) ; do \
+	    if echo "$$f" | grep -q translations ; then \
+	        if pdffonts $$f | grep -q -i cjk ; then \
+		    if pdffonts $$f | grep -q -i sarasa ; then \
+	                echo "$$f: with CJK pages with sarasa mono" ; \
+	            else \
+	                echo "$$f: with CJK pages" ; \
+	            fi \
+	        else \
+	            echo "$$f: without CJK pages" ; \
+		fi \
+	    fi \
+	done
+else # PDFFONTS_CMD
+	@echo '"pdffonts" unavailable.'
+endif # PDFFONTS_CMD
 
 .PHONY: $(ALLLATEXDIRS) symlink-pdf check-pdf
